version: '3'

services: 

  wppconnect-server:
    build: 
      context: ./wppconnect-server
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server
    hostname: wppconnect-server
    entrypoint: docker-entrypoint.sh yarn dev
    networks: 
      - wpp-network
    tty: true
  
  wppconnect-front:
    build: 
      context: ./wppconnect-front
      dockerfile: Dockerfile
    image: wppconnect-front
    hostname: wppconnect-front
    entrypoint: docker-entrypoint.sh yarn start
    networks: 
      - wpp-network
    tty: true
    depends_on:
      - wppconnect-server

  wppconnect-nginx:
    build: 
      context: ./wppconnect-nginx
      dockerfile: Dockerfile
    entrypoint: nginx -g "daemon off;"
    networks: 
      - wpp-network
    depends_on:
      - wppconnect-front

networks: 
  wpp-network:
    name: wpp-network
    driver: bridge 
